services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ./db/sqlite:/rails/db/sqlite
      - ./data:/rails/data:ro
      - ./storage:/rails/storage
