default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  pragmas:
    journal_mode: wal
    synchronous: normal

development:
  primary:
    <<: *default
    database: storage/bundessuche_development.sqlite3
  queue:
    <<: *default
    database: storage/queue_development.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: storage/bundessuche_test.sqlite3
  queue:
    <<: *default
    database: storage/queue_test.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: storage/bundessuche_production.sqlite3
  queue:
    <<: *default
    database: storage/queue_production.sqlite3
    migrations_paths: db/queue_migrate
