service: quellenportal

image: teal-bauer/quellenportal

servers:
  web:
    - 100.91.49.44

proxy:
  ssl: false
  host: quellenportal.de,archivfinder.de
  app_port: 3000
  forward_headers: true

error_pages_path: public

registry:
  server: ghcr.io
  username: teal-bauer
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MEILISEARCH_HOST
    - MEILISEARCH_API_KEY
  clear:
    WEB_CONCURRENCY: 2
    SOLID_QUEUE_IN_PUMA: false

volumes:
  - "quellenportal_storage:/rails/storage"
  - "quellenportal_data:/rails/data"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    host: 100.91.49.44
    port: "127.0.0.1:7700:7700"
    env:
      clear:
        MEILI_ENV: production
        MEILI_NO_ANALYTICS: "true"
      secret:
        - MEILI_MASTER_KEY
    directories:
      - meili_data:/meili_data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  download: app exec "bin/rails data:download"
  import: app exec "bin/rails data:import"
  reindex: app exec "bin/rails data:reindex"
